### ISSUE TITLE
Beginner question?

### ISSUE THREAD

**Issue by arjenpdevries** [maxmcd/webtty#1]
I run webtty in two xterms, and they seem to connect but then I only get lines with:

`inbound isControlling && a.isControlling == true`

Maybe I am not using it right, but this was my first test :-)

**Comment by arjenpdevries** [comment]
I apologize, that is what I did wrong.

**Comment by backkem** [comment]
No worries, glad I could help.

@maxmcd Just a suggestion: You could guard against this issue by verifying the SessionDescription type instead of overwriting it on [client.go#L129](https://github.com/maxmcd/webtty/blob/master/client.go#L129). You would also need to add it to the encoding in pkg/sd thought.

**Comment by maxmcd** [comment]
I actually ran into that same error writing some tests and was trying to figure it out. Thanks @backkem, will do.
